### ISSUE TITLE
No [mediafile].meta.yaml in page folder

### ISSUE THREAD

**Issue by beamaria** [clivebeckett/grav-plugin-admin-addon-media-metadata#6]
If I understand well, the plugin should create a [mediafile].meta.yaml in the page folder of a blog post. So, for instance, if my image file is cat.jpg  I should find these 3 files in the folder:
-cat.md
-cat.jpg
-[cat.jpg] meta.yaml   and this file should contain something like this:

title: Cat playing with his toy
description: The other day, the cat got a new toy.
caption : Our cat playing with na new toy

But instead there is nothing like this. I saved both the media metadata window and the page and also cleaned the cache for images. Any other idea?

**Comment by clivebeckett** [comment]
Hi! Thank you for this note. Since I had tested the plugin successfully in several instances of Grav 1.6/Admin 1.9 and even one instance with Grav 1.5/Admin 1.8, I now tested it in 1.7.0-rc.8/Admin 1.10.0-rc.8 – and it is indeed not working there.

Are you working in Grav 1.7/Admin 1.10 as well?

It seems that uploading media files now works differently: in Grav <1.7/Admin <1.10 a media file was visible in the folder immediately – without saving the page. And when you deleted it, it was immediately gone. Now both things happen only when you save it. And apparently the `onAdminAfterAddMedia` event hook which is necessary for the plugin to work, is not being triggered anymore.

**Comment by beamaria** [comment]
Hi Clive, 
I work in localhost, GRAV 1.6.23, Admin 1.9.13 - (Mac Mojave, Chrome and Safari browsers)

**Comment by clivebeckett** [comment]
Hmm. This is where it works perfectly for me, also in a local version on a Mac. I just dropped an image into the Media Browser of a page (using Safari, just to make sure), and the Finder showed the image file in the page folder immediately as well as the [image.jpg].meta.yaml file, containing the following lines:
```
title: ''
alt: ''
caption: ''
```

Just to get to the bottom of it step by step: Is the Plugin visible and enabled in the Plugins section of your Admin area – as in the following screenshot?
![Screenshot_2020-04-08 Grav Plugins](https://user-images.githubusercontent.com/36693867/78803746-a6a88d80-79bf-11ea-81b0-529bbbfdc361.png)

**Comment by beamaria** [comment]
Ok, I think I found the problem, if there is already an image in the page the plugin doesn't add a metadata.yaml file. I cancelled the existing image, then imported it again, opened the info window, put some content and save. The metadata.yaml file is now present in the folder. 
It looks like basically works only when you import the media for the first time

**Comment by clivebeckett** [comment]
Great, thank you. I am quite sure that in the first beta version it was still possible to write the meta.yaml files for images that were already there – this functionality must have gotten lost in one of the updates towards v1.0 :) I’ll check and see if I can manage to get it back in.

Solving the issue for Grav 1.7/Admin 1.10 will be much harder :)

**Comment by clivebeckett** [comment]
[Release 1.0.1](https://github.com/clivebeckett/grav-plugin-admin-addon-media-metadata/tree/v1.0.1) solves that problem: once you save meta data for a media file that does not have an associated meta.yaml yet, the plugin will create that file. Thanks for pointing me to it, @beamaria
